### ISSUE TITLE
Error when Running the Program to get Data

### ISSUE THREAD

**Issue by JLP04** [StateOfCalifornia/CalCAT#15]
When I do run all for al_cat_data_routine.rmd, I get the following error on the MOBS section: 
> mobs <- grab_mobs()
Error: lexical error: invalid char in json text.
                                                 saved_old_versions/mobs_New Yor
                     (right here) ------^

Note: the arrow should be under the a in saved

**Comment by vargoCDPH** [comment]
fixed the grab_mobs function to handle New York and Washington, json can be downloaded directly here https://data-tracking-api-dot-mobs-2019-ncov-web.appspot.com/data?state=New York State&frequency=daily and added to the `saved_old_versions` directory manually, but will need to be manually updated.

**Comment by JLP04** [comment]
I'm still having this problem, even after deleting and re-cloning the repo.

**Comment by vargoCDPH** [comment]
are you able to save this json in the `saved_old_versions` folder?  Can you provide some more context for the error you are receiveing?

**Comment by JLP04** [comment]
I was able to save the file but I'm still getting the following error: 

<img width="632" alt="Screen Shot 2020-07-01 at 9 35 05 AM" src="https://user-images.githubusercontent.com/63068340/86250150-381e3a80-bb7e-11ea-8ca8-af745d2c232c.png">
